# Generated by Django 4.2 on 2024-07-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('eClass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eclass',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='teacher.teacher'),
            preserve_default=False,
        ),
    ]
