# Generated by Django 4.2 on 2024-07-28 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eClass', '0002_eclass_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='eclass',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
