# Generated by Django 4.2 on 2024-07-24 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('eClass', '0001_initial'),
        ('myapp', '0003_feeparticulars_fee_class_feeparticulars_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeparticulars',
            name='fee_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeParticulars', to='eClass.eclass'),
        ),
        migrations.RemoveField(
            model_name='feeparticulars',
            name='students',
        ),
        migrations.AddField(
            model_name='feeparticulars',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='feeParticulars', to='student.student'),
        ),
    ]
