# Generated by Django 4.2 on 2024-07-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('myapp', '0004_alter_feeparticulars_fee_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeparticulars',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='feeParticulars', to='student.student'),
        ),
    ]
