# Generated by Django 4.2 on 2024-07-27 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingsystem',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_system', to=settings.AUTH_USER_MODEL),
        ),
    ]
