# Generated by Django 4.2 on 2024-07-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_gradingsystem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradingsystem',
            name='institute',
        ),
    ]
